// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bugxsezxtodwlyivwgwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Z3hzZXp4dG9kd2x5aXZ3Z3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTM2NTQsImV4cCI6MjA2MTU2OTY1NH0.Q745EAgPeJ8SuHDyxJPt7Ypy01YazrdBHPtxuzmZL9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);